### ISSUE TITLE
Large number of queries made for canView checks

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-graphql#117]
A screenshot of the number of queries made for a `/graphql` call in `asset-admin` :)

![screen shot 2017-09-04 at 11 12 35 am](https://user-images.githubusercontent.com/1064889/30007450-c09f2cdc-9162-11e7-8052-773a57d354ae.png)

From @tractorcow:
> So the crux of the story is for graphql to use `File::singleton()->getPermissionChecker()->canViewMultiple($ids)` instead of `foreach(File::get() as $file) $file->canView()`

**Comment by unclecheese** [comment]
Seems like this is an `asset-admin` issue, no? The only time this would be relevant in this module is in the scaffolded read resolver, which, as of now, does a simple singleton `canView` check. 

https://github.com/silverstripe/silverstripe-graphql/blob/master/src/Scaffolding/Scaffolders/CRUD/Read.php#L39

**Comment by tractorcow** [comment]
Fix for asset-admin at https://github.com/silverstripe/silverstripe-asset-admin/pull/621
