### ISSUE TITLE
Issue with basic scaffolding?

### ISSUE THREAD

**Issue by JustinTBrown** [silverstripe/silverstripe-graphql#140]
## Summary

> Also, in the silverstripe-graphql documentation the example given for querying via URL, /graphql/?query={readMembers{ID+FirstName+Email}}, does not include edges or nodes. Is this because queries are setup differently between scaffolded and non-scaffolded implementations?

## Acceptance Criteria

- It is clear in the example if pagination is turned off - or include pagination in the query.

## Details

I'm attempting to scaffold a basic DataObject into the schema, but my queries are throwing the following errors:

http://localhost:8080/graphql:

    {
      "data": null,
      "errors": [
        {
          "message": "Syntax Error GraphQL request (1:1) Unexpected <EOF>\n\n1: \n   ^\n",
          "locations": [
            {
              "line": 1,
              "column": 1
            }
          ]
        }
      ]
    }

And, http://localhost:8080/graphql/?query={readQuickPossessions{ID+Title+Address+SquareFeet}}:

    {
      "data": null,
      "errors": [
        {
          "message": "Syntax Error GraphQL request (1:25) Cannot parse the unexpected character \"+\".\n\n1: {readQuickPossessions{ID+Title+Address+SquareFeet}}\n                           ^\n",
          "locations": [
            {
              "line": 1,
              "column": 25
            }
          ]
        }
      ]
    }

I've also tried properly formatted GraphQL (which throws the same error above):

```
query {
	readQuickPossessions{
		ID
		Title
		Address
		SquareFeet
	}
}
```

Here is the DataObject:

    <?php
    namespace Trigger\HomeBuilderSite\DataObjects;

    use SilverStripe\ORM\DataObject;
    use SilverStripe\GraphQL\Scaffolding\Interfaces\ScaffoldingProvider;
    use SilverStripe\GraphQL\Scaffolding\Scaffolders\SchemaScaffolder;

    class QuickPossession extends DataObject implements ScaffoldingProvider {
      private static $table_name = 'QuickPossession';

      private static $db = [
        'Title' => 'Varchar(255)',
        'Address' => 'Varchar(255)',
        'SquareFeet' => 'Int',
      ];

      private static $has_one = [];

      public function provideGraphQLScaffolding(SchemaScaffolder $scaffolder) {
        $scaffolder
          ->type(QuickPossession::class)
            ->addFields([
              'ID', 
              'Title',
              'Address', 
              'SquareFeet'
            ])
            ->operation(SchemaScaffolder::READ)
              ->end()
            ->operation(SchemaScaffolder::UPDATE)
              ->end()
            ->end();
        return $scaffolder;
      }
    }

And in mysite.yml:

    SilverStripe\GraphQL\Controller:
      schema:
        scaffolding_providers:
          - Trigger\HomeBuilderSite\DataObjects\QuickPossession

I've also tried the config-based approach, but with the same result. Any insights into what I'm missing? I've also [posted on Stack](https://stackoverflow.com/questions/48751480/silverstripe-graphql-syntax-error) as I wasn't sure of the best place for this issue.

**Comment by unclecheese** [comment]
By default, the `READ` operation is paginated.

```
query {
  readQuickPosessions {
    edges {
       node {
         ID
         Title
       }
    }
    pageInfo {
       hasNextPage
    }
}
```

Using a tool like [graphql devtools](https://github.com/silverstripe/silverstripe-graphql-devtools) will help you build your queries in adherence to the schema.

**Comment by JustinTBrown** [comment]
Thanks @unclecheese! I was missing the edges and node. Although this query didn't seem to require the pagination-related fields.

Also, in the [silverstripe-graphql](https://github.com/silverstripe/silverstripe-graphql) documentation the example given for querying via URL, `/graphql/?query={readMembers{ID+FirstName+Email}}`, does not include edges or nodes. Is this because queries are setup differently between scaffolded and non-scaffolded implementations?

The other reason my queries weren't working – and this is a bit of an aside – is that there appears to be a quirk with [Insomnia](https://insomnia.rest/), the API client I use. I had specified the content-type header as `application/graphql` since I'm supplying a query in GraphQL, which didn't work. However, when I changed the content-type to `application/json` the query worked. That's not what I had expected and will follow up with Insomnia about that.

**Comment by JustinTBrown** [comment]
Follow-up: there wasn't an [issue](https://github.com/getinsomnia/insomnia/issues/755#issuecomment-365161106) with Insomnia. `application/json` is the appropriate content-type for making GraphQL *requests*. You'd only use `application/graphql` for sending the *query only*.

**Comment by flamerohr** [comment]
the example could probably do with an update or clarification note :)

I've added that as an AC for this issue to be actioned.

**Comment by unclecheese** [comment]
All the examples are correct, except for one on the `1.0` branch. Have patched.

https://github.com/silverstripe/silverstripe-graphql/pull/141
