### ISSUE TITLE
OperationScaffolder::addArgs should allow types instead of declarative string inputs

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-graphql#153]
Quote @unclecheese "addArgs should allow types instead of just declarative string inputs"

For the current history viewer work I need to be able to apply the `VersionedInputType` argument to the nested Versions subquery that silverstripe/versioned attached to versionable DataObject read operations.

Example of modified HistoryViewer query for the CMS: https://gist.github.com/robbieaverill/261d09b0b34f04e0684d16a5cc213108/revisions

## Pull Request
- [ ] https://github.com/silverstripe/silverstripe-graphql/pull/168

**Comment by unclecheese** [comment]
`->addArgs('MyArg', $myInputType)` should work

We'll have to consider how that affects the Manager, though.  Would probably have to scan the arg list on addToManager and register any input types that have been added.

**Comment by maxime-rainville** [comment]
@robbieaverill Is this still a blocker for you? Should we put an higher priority on it?

**Comment by robbieaverill** [comment]
@maxime-rainville its tied to https://github.com/silverstripe/silverstripe-versioned/issues/147 which combined will be a blocker for anyone on a large project using the history viewer/versioned-admin module

**Comment by maxime-rainville** [comment]
Ok. Throw some angry passive-aggressive comments at Ingo if you feel it needs be an higher priority.

**Comment by robbieaverill** [comment]
As a a similar follow up to this, I can't apply the VersionedInputType to a versioned DataObject. I can apply it to the Versions field underneath it, but for example I can't do this:

```graphql
query getBlocksForPage($id:ID!) {
  readOnePage(ID: $id, Versioning: {
    Mode: LATEST
  }){
    ID
    ElementalArea {
      Elements {
        pageInfo {
          totalCount
        }
        edges {
          node {
            ID
            Title
            Summary
            Publisher # Cannot query field "Publisher"...
          }
        }
      }
    }
  }
}
```

`Published` is only available on the nested `Versions` list underneath that. I'm super hesitant to use that subquery list because it's immediately executed so would kill anyone's website when used in the context of what I'm working on. Related: https://github.com/silverstripe/silverstripe-versioned/issues/147
