### ISSUE TITLE
Type introspection should fail gracefully on empty schema

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#157]
If you don't have `asset-admin` (or `versioned-admin`) installed, chances are you have no schema defined (e.g. nothing in `Manager`). This means that the `/graphql/types` endpoint, as well as the creation of the static `types.graphql` file, will fail fatally.

Potential fix is to do some detection up front to see if there are types defined before executing the query. If not, we need to return some kind of 200 response. One option would be:

```php
json_encode([
  '__schema' => [
    'types' => []
  ]
]);
```

But that feels like a bit of a hack. Not sure.

**Comment by emteknetnz** [comment]
I'm going to assume this is resolved as linked PR was merged https://github.com/silverstripe/silverstripe-admin/pull/523
