### ISSUE TITLE
Update to use webonyx/graphql-php server features

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-graphql#186]
Consider updating the core graphql lib to a more recent version

Later versions of webonyx/graphql-php have moved towards using a [Server](http://webonyx.github.io/graphql-php/executing-queries/#using-server) object to support features like persistence and [batching](http://webonyx.github.io/graphql-php/executing-queries/#query-batching) rather than a straight call to `executeQuery`. 

There are also some performance gains to be had from features like [lazy schema evaluation](http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations)

version 0.11 is the last to support < php 7. 

I've made a start on updating the dependency [here](https://github.com/blueo/silverstripe-graphql/tree/feature/graphql-upgrade-0.11) but haven't yet validated all the breaking changes from the [update docs](https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md).

the server implementation could be interfaced with using PSR-7 and so relates to [this discussion also](https://github.com/silverstripe/silverstripe-framework/issues/6514)

**Comment by riddler7** [comment]
Also, the current version isn't compatible with PHP 7.3. It looks like at least 0.12 is required for 7.3 support (use of continues in switch statements).

**Comment by maxime-rainville** [comment]
We have some support constraint related to this. https://github.com/silverstripe/silverstripe-framework/issues/8556#issuecomment-445085441

The current strategy is:
> Bump SS 4.x PHP requirements to PHP 7.1+ sometime in 2019 (months past the official EOL for PHP 5.x) - apply to next minor release, and keep current minor releases PHP 5.6+ compatible

**Comment by blueo** [comment]
@robbieaverill  I'd be happy for this to close :) Looks like some nice changes to play with - looking forward to it.
