### ISSUE TITLE
Add cache_types_in_filesystem=true breaking flush

### ISSUE THREAD

**Issue by shot131** [silverstripe/silverstripe-graphql#203]
Adding SilverStripe\GraphQL\Controller:cache_types_in_filesystem: true to _config.yml break flush with error
> ERROR [Emergency]: Uncaught Exception: There was an error caching the GraphQL types: Request method must be POST or GET

**Comment by robbieaverill** [comment]
Reproduced on SS 4.3.0:

* Add config to app/_config/_config.yml
* Flush in the browser
* Flush in CLI

Both flushes fail with this error.

**Comment by maxime-rainville** [comment]
That got introduced by https://github.com/silverstripe/silverstripe-graphql/pull/194.

I'm thinking, it might just be a question of updating `Controller::writeSchemaToFilesystem()` to pass along some dummy request when it calls getManager().

https://github.com/silverstripe/silverstripe-graphql/blob/b1e3c42c2721d5562fed00a29741364bff8bdd9e/src/Controller.php#L399-L412

**Comment by lekoala** [comment]
Or also maybe that HTTPMethodMiddleware class could be more conservative and not throw exceptions if nothing is set in $context['httpMethod]. Currently, the context is empty and therefore is not GET or POST. And don't see the added value of applying middlewares on a fake request anyway.
