### ISSUE TITLE
Allow mutations to opt out of CSRF protection

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#212]
The https://github.com/Firesphere/silverstripe-graphql-jwt module uses mutations to create a JWT. JWT should be used to avoid on stateful requests with PHP sessions. At the moment, `CSRFMiddleware` enforces CSRF in all mutations. CSRF tokens are created by starting a PHP session. This is not ideal.

The short term solution is to allow mutations to opt out of CSRF protection. In this case, the submission relies on authentication parameters which an attacker couldn't fake, so it's technically safe from CSRF already.

The long term solution is to not rely on PHP sessions for authentication, and use JWT as a stateless HTTP request authentication in the first place. Then your JWS *is* your CSRF protection, assuming it's stored in localstorage and not automatically sent along with requests that an attacker might trigger for victims.

See https://github.com/Firesphere/silverstripe-graphql-jwt/issues/22 for the related bug in firesphere/graphql-jwt

**Comment by unclecheese** [comment]
This can probably be closed. But since I did the PR, I'll wait for someone else to confirm.

https://github.com/silverstripe/silverstripe-graphql#disabling-csrf-protection-for-token-based-authentication-only
