### ISSUE TITLE
500 error visiting admin/graphql/types

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-graphql#218]
If you just visit the url admin/graphql/types, you get a 500 error, and e.g. a Raygun error.

This should bee a 4xx level error, maybe 400, and not throw an exception.

Occurs in 3.x

**Comment by unclecheese** [comment]
I'm not able to replicate this. Using the `3` branch:
* If the `IntrospectionProvider` extension is applied to `Controller`, I get a JSON response when acceessing `/admin/graphql/types` in the browser.
* If not applied, I get a 404 error page.

**Comment by sminnee** [comment]
I believe you need to have framework, admin, and GraphQL installed but not cms, asset-admin, or campaign-admin. Did you do that?

**Comment by sminnee** [comment]
Ps see the referenced PR

**Comment by unclecheese** [comment]
Ah, thanks. Sorry, missed that.

**Comment by sminnee** [comment]
Fixed in #219.
