### ISSUE TITLE
SchemaScaffolder doesn't (seem) to support magic methods

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-graphql#234]
One of the great things about SilverStripe is that developrs can declare a field, and then overload it with a custom getter or a public method with a corresponding name, which normally happens through `ViewableData::__get()`

In my limited experience with this module, this is not possible (directly) when attempting the same. Very possibly, this is the job of a custom resolver (like I said, I'm a noob), but as a long-time SilverStripe dev, I'd expect the first example (below) to work OOTB, instead I have to declare the name of the override method myself.

**Examples:**

```php
class Wibble extends DataObject
{
	private static $db = [
	  'Foop' => DBVarchar::class,
	];

	public function provideGraphQLScaffolding(SchemaScaffolder $scaffolder)
	{
		$scaffolder
		    ->type(Wibble::class)
		    ->addFields([
		    	'Foop'
		    ]);

		return $scaffolder;
	}

	// GraphQL: null
	public function Foop()
	{
		return 'Test #1';
	}

	// GraphQL:  null
	public function getFoop()
	{
		return 'Test #2';
	}
}
```

```php
class Wobble extends DataObject
{
	private static $db = [
	  'Feep' => DBVarchar::class,
	];

	public function provideGraphQLScaffolding(SchemaScaffolder $scaffolder)
	{
		$scaffolder
		    ->type(Wobble::class)
		    ->addFields([
		    	'getFeep'
		    ]);

		return $scaffolder;
	}

	// GraphQL: null
	public function Feep()
	{
		return 'Test #1';
	}

	// GraphQL: 'Test #2'
	public function getFeep()
	{
		return 'Test #2';
	}
}
```

**Comment by maxime-rainville** [comment]
Can you post your scaffolding logic?

Off the top of my head, I'm thinking you might need to define what Feep/Foop methods are returning using `private static $casting = ["Magick" => 'Text'];`. Otherwise, SilverStripe won't know what type to assign the field in your grpahql schema.

**Comment by chillu** [comment]
No feedback, closing. I believe this is possible in GraphQL v4 now either way.
