### ISSUE TITLE
Don't use SilverStripe\Core\Object

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-graphql#26]
Object is a reserved work in PHP 7.2 and we'll want to remove the Object class entirely before SS 4 stable is out.

Don't use it as a base class.

If you need its facilities, use the various traits that it's composed of.

**Comment by sminnee** [comment]
Object is a reserved work in PHP 7.2 and we'll want to remove the Object class entirely before SS 4 stable is out.

Don't use it as a base class.

If you need its facilities, use the various traits that it's composed of.

**Comment by wilr** [comment]
Makes sense.
