### ISSUE TITLE
GraphQL 4: "Flushless" YAML?

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#268]
Per the [comment](https://github.com/silverstripe/silverstripe-graphql/pull/266#issuecomment-675843770) on the [GraphQL 4 pull request](https://github.com/silverstripe/silverstripe-graphql/pull/266):

> Something to think about re: the dev experience.. So much of the dev experience is through yaml now. We’re using the config layer for that, which means all changes have to be flushed. But this config never gets consumed at runtime. Which means it doesn’t need to be cached.

> It would make a lot more sense if these yaml files were not part of config, but that may confuse people. Say, for instance, we have a _graphql/myqueries.yml file -- location could be configurable. But basically, all we need to do is turn that document into an array and load the schema at build time. This is way faster. Right now, the config layer is doing very little other than adding latency to the build task due to the required flush.

> You’d lose all the recursive merging, but few apps have their schemas modified by thirdparty config anyway. Maybe you could opt into a "flushless schema" if you accept there is a single source of truth.

```
SilverStripe\GraphQL\Schema\Schema.mySchema:
  properties:
    configSrc: `app/_graphql` # gather *yml from this directory and bypass Config
```

> The benefits to this are huge. You can run a clean build task every time without ever worrying about flushing. It's not super intuitive that adding a field to a dataobject or adding a new resolver requires a flush.

> It's also fair to say that a decent sized project will have a lot of these yaml files defining schema. It might get cumbersome colocating them with all the other config.

@chillu : "I think that's a pretty big assumption, particularly as we're creating more GraphQL coverage for CMS usage. For example, anything that needs new UI features in AssetAdmin right now (e.g. focus points on thumbnails) needs to modify the admin/graphql schema. So I can't see how any system could opt into a "flushless" admin schema. It could be a nice DX improvement for your own schemas, but I don't see it as a solution for 18s build times."

@unclecheese " Well to be clear, it's not a mitigation for 18s builds. Those aren't going anywhere (assuming full build, not incremental). But it is a potential solution to minimise the time from running the task to getting a new schema overall. For a medium sized schema, you spend more time on the flush than you do on the build, and for an incremental build, you'll always spend more time on the flush than the build.

`admin/graphql` is certainly not the intended use case, but for your own app, I think an opt-in makes sense."

**Comment by unclecheese** [comment]
Technically, recursive merges aren't out of the question.

```
SilverStripe\GraphQL\Schema\Schema.mySchema:
  properties:
    sources:
      app: app/_graphql
      cms: cms/_graphql
```

All the schema needs is a big array. `array_merge_recursive` is a thing. :-)

You wouldn't even lose the "before" / "after", because you'd be using the config layer itself to define the order of `sources`.

**Comment by unclecheese** [comment]
You could even add a watch task, maybe as a separate module. And then schema builds become like babel builds. Not super intuitive to say "I'm doing graphql, better start up the watch task", but the alternatives aren't great, either. We have a DX issue no matter how we slice it.

**Comment by unclecheese** [comment]
Have added this here: https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/81183241b46c98f16e177468230ad233d7da4200

**Comment by chillu** [comment]
Nice! @unclecheese what's the effect on rebuild times? Have you noted this in docs as well? Should we move existing module  graphql definitions to the same format? Otherwise it'll be hard to influence module config in other modules or custom code right?

**Comment by unclecheese** [comment]
Yeah the module config has all been moved to flushless. Docs assume you're using flushless. 

Build times aren't affected by this directly. But you save the delay of a flush when you modify the schema, so basically, 90% of the time, it's  "flush seconds" faster. 😋
