### ISSUE TITLE
GraphQL 4: Do type caching in build step?

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#270]
Right now, we need to get a schema introspection file to Apollo on CMS load so that it can disambiguate unions and interfaces. This is accomplished with a very ham-handed approach, using a flush task that persists to the assets/ directory.

If graphql schemas require a build step anyway, why not persist this introspection file to the assets/ directory while we're in there? Would clean up a lot of ugly code.

**Comment by robbieaverill** [comment]
I'm not super familiar with the context, but it sounds like your suggestion is the same as what's described as current behaviour

**Comment by unclecheese** [comment]
Yeah, didn't explain it very well, but basically, status quo is that we do this on flush. Doesn't matter if the schema changes or not. We just do it regardless. This would move the side effect to the actual schema build, so that you're generating that file at the proper time, which is when the schema changes.

It would move all this work to the build task where it belongs, rather than awkwardly in controller logic.

**Comment by robbieaverill** [comment]
Okay, sounds good!

**Comment by unclecheese** [comment]
Type caching is now a service that gets called by an event handler in 4.0.0-alpha1 https://github.com/silverstripe/silverstripe-graphql/releases/tag/4.0.0-alpha1
