### ISSUE TITLE
Operations on nested type definitions are too ambiguous

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#287]
I'm reading the [docs](https://pulls-master-schemageddon--ss-docs.netlify.app/en/4/developer_guides/graphql/working_with_dataobjects/nested_definitions/) on nested type definitions, and I reckon it's too ambiguous to allow defining `operations` there. It's too easy to assume that those operations will only be available in the context of the parent records, rather than globally.

To stick with the `Blog.Authors` example, a developer might be fine to have `operations: ['read']` on *blog authors*, but in effect this creates a `readMembers` query which will *also* allow reading all other `Member` records in the system - often way more than those who are just blog authors. 

I think the benefit of saving a line of YAML is not worth the risk of people misunderstanding this.

**Comment by unclecheese** [comment]
https://github.com/unclecheese/silverstripe-graphql/commit/c163c975a0da5c31cedfdb92cbaaa38d94556a3e

https://github.com/unclecheese/silverstripe-framework/commit/7955a0c844e42434b6fe40f9c72e31e9dbc5e42f
