### ISSUE TITLE
Custom pluralisation on read and delete operations

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#288]
The `Schema::pluralise()` default implementation will not handle all vagaries of the English language (just be thankful it's not German!). We should allow to overwrite that name. Doesn't look like anything else relies on this being a "predictable" name (inferring by calling `Schema::pluralise()`)

**Comment by unclecheese** [comment]
That's fine. We'll make this a configurable callable like the typeName generator.

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/b2f5830bf6841730dd4c31ea54f7a382c320700b

Docs: https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/3954b5c482dde2cc5223466f4f9b2e02729d5bdd
