### ISSUE TITLE
CodeGenerationStore->persistSchema() should be atomic

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#293]
At the moment, it incrementally overwrites files. If the execution breaks halfway through, this leaves you in a broken state for the schema. But more importantly, if we want to support a use case of running schema generation *on the production server* after deployment, this will lead to API errors and downtime during regeneration. Our favoured approach is to bundle the generated schema into the deployment package, at which point the atomicity is handled by your deployment mechanism (usually symlink or load balancer switching).

**Comment by unclecheese** [comment]
Right. Easiest solution here is to write to the temp folder and swap it, like a deployment.

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/b42e3f95421c69a0628697cd5f54f5ad9d99fc25
