### ISSUE TITLE
Use Page instead of SiteTree in example code

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#294]
I just hate seeing `readSiteTrees()` :D For anyone using the CMS, their "base unit" will be the `Page` class. Not only does `readPages()` feel a lot more natural for a Content API, it also means you don't have to use `__extends` for a good chunk of the fields used in your project (which tend to be on the `Page` class).

Potential concerns:
 * In CWP we have `class Page extends CWP\CWP\PageTypes\BasePage`, so you'd be inlining more fields into the base type. I don't see that as an issue.
 * Custom namespace for `Page`. Even in this case, our [accepted solution](https://github.com/silverstripe/silverstripe-framework/issues/5844) is to still have an un-namespaced `Page` class. So having schemas generally expose `Page` rather than `SiteTree` in their `model` definition seems feasible.
 * Example code gets more confusing: If we stick with `Page`, it's not clear that you need a FQCN. We could fix that by preferring custom DataObjects in examples? Would also help to decouple the instructions from the CMS use case a bit.
 * Projects without a `Page` class in their project code - is that even possible?

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/14fc8b503094ae150ed80ab052ab03e7cac7e248
