### ISSUE TITLE
Field limitations are not respected on create and update operations

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#297]
It seems to choose all fields by default. Which seems reasonable, but is worth pointing out explicitly in the docs. 

In terms of building a locked-down custom API (rather than a CMS Admin API), you'll usually want to limit fields though - e.g. not allowing to set `Comment.IsModerated`. While you could do this through model level validation based on member permissions, it feels a bit messy to have this field available for a frontend commenting API.

It looks like you can add some fields to `exclude` for a specific operation. Could we alternatively allow `fields` to be defined there as well? Feels a bit weird to have a `fields` allowlist on a type level, and then an `exclude` blocklist on an operation level.

Rough example.

```php
<?php
class MyModel extends DataObject {
  protected static $db = [
    "MyField" => "Text",
    "ReadonlyField" => "Text",
    "RestrictedField" => "Text",
  ];
}
```

Before:

```graphql
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        MyModel:
          fields:
            id: true
            myField: true
            readonlyField: true
          operations:
            read: true
            create:
              exclude:
                - id
                - readonlyField
                - restrictedField
            update:
              exclude:
                - id
                - readonlyField
                - restrictedField
```

After

```graphql
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        MyModel:
          fields:
            id: true
            myField: true
            readonlyField: true
          operations:
            read: true
            create:
              fields:
                myField: true
            update:
              fields: 
                myField: true
```

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/deb36aa228eb3925e8396ef08a605787ba357a85
https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/61bb4a9aaec145bf25f7248a0b3725cce8113960
