### ISSUE TITLE
Nested fields do not respect canView permission checks

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#298]
When nested fields expose relationships, the module assumes you "inherit" the `canView` permission from the base type, and doesn't run them on the specific types. This might be desireable given the performance implications, but we should point that out as a big caveat in the docs when using nested fields.

Note that we also need to consider that if we decide to allow nesting on create/update operations.

**Comment by unclecheese** [comment]
This one should be fixed here https://github.com/silverstripe/silverstripe-admin/pull/1088/commits/e01a119ae0dbdcfe97630e4f1251984a1db73f57

Just ensure that the relation list is also canView filtered.
