### ISSUE TITLE
Support for versioning and stages

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-graphql#30]
Queries and manipulations need to work with the `Versioned` ORM add-on:

## Required operations

Queries

 * Queries by stage: draft/published ("Stage" and "Live")
 * Queries of content as at a historical date
 * Queries of content that are in a specific stage and don't exist on any other stage
 * Query content including deleted items
 * Query a specific version of a single record
 * Query all versions of a single record

Mutations

 * Write to a specific stage
 * Overwrite a specific version? (not sure if this is internal only)
 * Various workflow actions (publish, rollback, etc)

## Usage considerations

 * Powering the asset-admin and campaign-admin UIs in SS4
 * Generic content API for building rich JS apps, mobile apps, etc

## Possible implementation approaches

 * Different GraphQL end-point URLs for different stages.
 * A new GraphQL type for a stage and/or archive date that has the core content types as nested objects.
 * Extra parameters to queries and mutations for selecting stages, dates, versions
  
## Acceptance Criteria (WIP)

* All operations accept an optional parameter that defines the stage for the operation
* Stage parameter is not added if `versioned` is not installed
* No new scaffolded operations are added for reading/writing from stages
* For mutations, a reference to a version should suffice if no fields are being changed
* `Version` is exposed on all versioned data objects when `versioned` is installed
* `versioned` module provides new query for getting historical content
* Existing queries for versioned objects are backward compatible 
* Apollo can distinguish between records with duplicate IDs across different versions.

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/83
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/128
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/727
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/133

**Comment by chillu** [comment]
> Version is exposed on all versioned data objects when versioned is installed

@unclecheese Can we make this opt-out? I think there'll be public GraphQL endpoints which only want to expose a subset of properties and operations, and mask the fact that the object is versioned in the first place (or that historical versions exist).
