### ISSUE TITLE
DOCS: Add "opt out" of versioning docs

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#320]
Per @chillu 's [comment](https://github.com/silverstripe/silverstripe-versioned/pull/308#discussion_r520955450) on `silverstripe-versioned` updating the global schema:

> Adding this to all schemas by default encourages the use of previews in your implementation, but also increases the security surface of your API. Given it's non-trivial to opt out of this, I think we need to add more docs on an "opt out config"

We should document how to turn off versioning, since injecting it into all schemas is a bit aggressive.

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/9769
