### ISSUE TITLE
GraphQL v4: Elemental GridField reordering "drop" indicator is missing

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-graphql#323]
Previous version when you begin a drag/drop action with a block, you get an indicator to tell you where you are about to drop the item.

![Screen Shot 2020-11-13 at 11 13 37 AM](https://user-images.githubusercontent.com/505788/99002498-5f136100-25a1-11eb-9592-82ea74f9a641.png)

This indicator appears to be missing at the moment.

![Screen Shot 2020-11-13 at 11 15 08 AM](https://user-images.githubusercontent.com/505788/99002615-91bd5980-25a1-11eb-9624-01d7f38a0f59.png)

## Pull requests
- [ ] https://github.com/dnadesign/silverstripe-elemental/pull/853

**Comment by unclecheese** [comment]
Fixed here: https://github.com/dnadesign/silverstripe-elemental/pull/853
