### ISSUE TITLE
Autobuilding broken on first dev/build

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#331]
Autobuilding on dev/build doesn't seem to find all config for a schema, e.g. `asset-admin/_graphql/*`.

```
composer create-project silverstripe/installer test 4.x-dev
cd test

# Not found after autobuild
vendor/bin/sake dev/build
ls -ahl .graphql/admin/ | grep FileUsage

# Not found after cached manual build
vendor/bin/sake dev/graphql/build 
ls -ahl .graphql/admin/ | grep FileUsage

# Found after cleared manual build
vendor/bin/sake dev/graphql/build clear=1
ls -ahl .graphql/admin/ | grep FileUsage
-rw-r--r--   1 ingo  staff   1.2K 27 Nov 17:38 FileUsage.php
```

**Comment by chillu** [comment]
Moving out of epic, most likely fixed through https://github.com/silverstripe/silverstripe-graphql/pull/352

**Comment by unclecheese** [comment]
The above refactoring doesn't fix it. This was caused by an incorrectly constructed CacheInterface instance, resulting in shared build cache across projects.


https://github.com/silverstripe/silverstripe-graphql/commit/4011f0d815b47702e733506ad9e4f9785c111fda
