### ISSUE TITLE
GraphQL v4: Filter `in` ignored

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-graphql#336]
When querying for a set of dataobjects with the `in` filter on ID, the filter is ignored.

eg with this yml
```
DNADesign\ElementalList\Model\ElementList:
  fields:
    "*": true
  operations:
    readOne: true
    read: true
```

and this query: 
```
{
  readElementLists(
    filter: { id: { in: ["27"] } }
    versioning: { mode: DRAFT }
    sort: { sort: DESC }
  ) {
    nodes {
      id
      title
      __typename
    }
  }
}

```

 I get a response that returns all ElementList objects:
```
{
  "data": {
    "readElementLists": {
      "nodes": [
        {
          "id": "10",
          "title": "Activity start title",
          "__typename": "ElementList"
        },
        {
          "id": "27",
          "title": "Group 1",
          "__typename": "ElementList"
        },
        {
          "id": "19",
          "title": "Checklist activity",
          "__typename": "ElementList"
        }
      ]
    }
  }
}
```

I would have expected to only have got the object with id "27" back.

Using the 'eq' filter works as expected. 

On commit `7584bdafa222e1419113ba6991b45fb683ef68e7`

**Comment by emteknetnz** [comment]
@blueo do you have the same issue in graphql 3?

**Comment by blueo** [comment]
@emteknetnz not that I know of. I don't have a graphql3 setup at the moment that i can test on unfortunately - I'll see if I can fire up an old project to test

**Comment by unclecheese** [comment]
Resolved here: https://github.com/silverstripe/silverstripe-graphql/commit/77a9996b28145f90e5769715a305c39787912e30

**Comment by blueo** [comment]
great! just tried it out and works for me!
