### ISSUE TITLE
GraphQL v4: Elemental Sorting not working

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-graphql#338]
We've got the latest graphql v4 (77a9996b28145f90e5769715a305c39787912e30) and elemental (e93c732964287eeb0fb455c1ad6c3bf68a02f251) installed and have noticed that drag/drop sorting isn't working.

I only seem to be able to drag an item to the first position. No mater where I drag an item, it appears at the top. It also persists after a reload, suggesting it isn't the JS state but the sort value that's incorrect

**Comment by unclecheese** [comment]
99% sure this will solve it: https://github.com/dnadesign/silverstripe-elemental/pull/853

Just waiting to make sure it's green.

**Comment by unclecheese** [comment]
@blueo Have merged that PR, and this appears to be resolved on my end. Can you confirm?

**Comment by blueo** [comment]
I can @unclecheese working well and looks great - thanks!
