### ISSUE TITLE
GraphQL v4: Empty responses also have an error

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-graphql#339]
I'm querying for sitetree objects with readOneSiteTree and when the response is a valid empty response (Eg no page exists / it is unpublished) I'm also getting an error response as it seems to be trying to apply 'canView' to the empty response:

![image](https://user-images.githubusercontent.com/948122/102264655-d199a700-3f7a-11eb-8a82-2b97bc36a4f3.png)

example query:

```
{
  readOneSiteTree(filter: { id: { eq: 5000 } }) {
    id
    title
  }
}
```

**Comment by unclecheese** [comment]
Have tested this again -- a `readOne` query for a non-existent ID with the canView plugin active, and can confirm it fails gracefully in 4.0.0-alpha1.
