### ISSUE TITLE
Remove BuildState global state

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#341]
The `BuildState` class gets passed around half a dozen classes as a "container" for a `Schema`, which is really just a fancy way of using a singleton (which might change over time, e.g. when multiple schemas are built in one process). Global state makes things harder to test and reason about, since it's a somewhat hidden dependency on consumers (e.g. `DataObjectModel` or `Field`).

Aaron suggested that this can be refactored by keeping it in the `$context` argument for resolvers.

**Comment by unclecheese** [comment]
Easiest path:

* `$context` gets a new `schemaConfig` key for easy access to type mapping, etc. No more `BuildState` in resolvers
*  `SchemaModelCreatorInterface` takes a `Schema` param in`createModel`, allowing models to have schema context
*  InheritancePlugin passes `Schema` to `InheritanceChain` service
* `Field` takes new `Schema` constructor arg
* Might as well do `Type`, for consistency

**Comment by chillu** [comment]
This is an example of why globals make things hard to maintain: The controller instanciates a schema, then calls `buildSchema()` with only the schema key, and not passing in the instance. Then it assumes the instance has been affected by the operation without replacing it. https://github.com/silverstripe/silverstripe-graphql/blob/master/src/Controller.php#L149

**Comment by unclecheese** [comment]
Yup, I think the whole reason you need to go through `Build` there is because of the global state it provides. If we got rid of the reliance on global state, that just becomes `$this->getSchema()->save()`.

**Comment by unclecheese** [comment]
Removed `BuildState`in 4.0.0 alpha! https://github.com/silverstripe/silverstripe-graphql/releases/tag/4.0.0-alpha1
