### ISSUE TITLE
TestOnly classes aren't in schema during unit test

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-graphql#354]
A unit test is failing in elemental because a TestOnly class is not is not in __type-mapping.php or SchemaContent::get('modelCreators')

```
1) DNADesign\Elemental\Tests\Reports\ElementsInUseReportTest::testReportShowsElementsInUse

TypeError: Return value of DNADesign\Elemental\Models\BaseElement::getGraphQLTypeName() must be of the type string, null returned
```
https://travis-ci.org/github/dnadesign/silverstripe-elemental/jobs/756184156

The reason `getGraphQLTypeName` is trying to return null is because `Schema::getTypeNameForClass(DNADesign\Elemental\Tests\Src\TestElement);` is returning null

https://github.com/dnadesign/silverstripe-elemental/blob/4/tests/Src/TestElement.php

**Comment by unclecheese** [comment]
This should be fixed now. Test is green https://travis-ci.org/github/dnadesign/silverstripe-elemental/builds/759315174

Can you confirm, @emteknetnz ?

**Comment by emteknetnz** [comment]
Yup have tested locally, can confirm this has fixed this issue
