### ISSUE TITLE
README.md isn't helpful 

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-graphql#356]
README isn't helpful at all and kinda time wasting.
To return the results first of all you need to implement Authorization.

Following the usage section this query never works:

```
{
  readMembers {
    edges {
      node {
        ID
        FirstName
        Email
      }
    }
  }
```

You should disable currentUser permissions check to see if it works and it will return an error:
It will return:
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field \"edges\" on type \"member\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

So you should use this query:
```
{
  readMembers {
    ID
    FirstName
    Email
  }
}
```

This query will return pagination details, but members at the edges field will be missing:
```
query Members {
  paginatedReadMembers(limit: 1, offset: 0) {
    edges {
      node {
        ID
        FirstName
        Email
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      totalCount
    }
  }
}
```

Because SilverStripe\GraphQL\Pagination at the line 406 has an extra permission check.

**Comment by a2nt** [comment]
so PaginatedQueryCreator has extra authorization check per object in the list while QueryCreator doesn't and it's unexpected behaviour

**Comment by chillu** [comment]
Hey @a2nt can you please check the new GraphQL v4 docs on http://docs.silverstripe.org/en/4/developer_guides/graphql/ and see if this is still an issue? We're not focusing a lot on GraphQL v3 any more.

**Comment by GuySartorelli** [comment]
Closing - there's been no response in many months, so I'm going to assume the new documentation resolves this for v4.
