### ISSUE TITLE
GraphQL 3 - s.fragmentMatcher is not a function

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-graphql#360]
Causes the files section of the CMS to not load due to a javascript error

silverstripe/graphql 3.x-dev 636c212
silverstripe/recipe-cms 4.x-dev 3e7ecaa

Travis build of `3` passed 7 days ago https://travis-ci.com/github/silverstripe/silverstripe-graphql/builds/216639540
Travis build of `3` failed 11 hours ago https://travis-ci.com/github/silverstripe/silverstripe-graphql/builds/217345512

Both have the same commit of graphql 636c212, so possible that it's something in the admin or asset-admin module that's broken.  The failing test are behat tests that have a BEHAT_SUITE of asset-admin

![image](https://user-images.githubusercontent.com/4809037/108280502-26f46d80-71e3-11eb-97fc-8bd6e546af14.png)

https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-graphql/217345512/483705445/screenshots/file-status-icons.feature_14.png

**Comment by emteknetnz** [comment]
Reverting admin to `"silverstripe/admin": "1.x-dev#57279ad20a467222656472586696aba586ad75a8"`

Fixed issue, so looks like it was something in one of these admin commits that needs a small tweak to resolve this

![image](https://user-images.githubusercontent.com/4809037/108281764-34aaf280-71e5-11eb-99ab-cef50ec8c523.png)

**Comment by unclecheese** [comment]
issue is in `getGraphQLFragments`, we assumed graphql 4. Need the old graphql 3 urls, too.

**Comment by unclecheese** [comment]
Fix is here https://github.com/silverstripe/silverstripe-admin/pull/1182

**Comment by emteknetnz** [comment]
Have merged linked PR

Have noticed that I'm getting a pair of 404's in elemental.  I don't think this impacts the ux but it looks pretty bad in the network panel

![image](https://user-images.githubusercontent.com/4809037/108441157-6c836a00-72b9-11eb-92e7-ac2274a6b664.png)

@unclecheese  What's your thoughts?

**Comment by unclecheese** [comment]
That's with Graphql 3, right?

**Comment by emteknetnz** [comment]
silverstripe/framework 4.x-dev c6d6358
silverstripe/graphql 3.x-dev 636c212
silverstripe/admin 1.x-dev 86728f9
dnadesign/silverstripe-elemental 4.x-dev 817c49c

**Comment by unclecheese** [comment]
Have replicated.. looking into it.

**Comment by unclecheese** [comment]
Fix is here: https://github.com/silverstripe/silverstripe-admin/pull/1184

**Comment by emteknetnz** [comment]
@unclecheese Reopening this one, there's now a similar issue with graphql 4 showing a 'null' request for elemental

![image](https://user-images.githubusercontent.com/4809037/108641043-f9206900-7501-11eb-8d36-73d185af6d32.png)

silverstripe/framework                    4.x-dev 5a4641d
silverstripe/admin                        1.x-dev cc80691
silverstripe/graphql                      dev-master 4011f0d
dnadesign/silverstripe-elemental          4.x-dev 817c49c

**Comment by unclecheese** [comment]
That damn `reverse()` call! 

https://github.com/silverstripe/silverstripe-admin/pull/1186
