### ISSUE TITLE
Remove legacyURLs in getGraphQLFragments()

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#384]
We shouldn't support legacy accumulated during an alpha stage

## Acceptance criteria
- References to legacy url and graphql legacy are removed from the codebase
- All our GraphQL logic is still functional.
- This change is made in the CMS 5 branches.

## Note
We don't think this will break anything in CMS 5 ... but if it does, just re-target the change to CMS 6 instead.

## Shared CI run
- https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/9560723853

Failures in shared CI run are existing, I've replicated them all running locally with a fresh 5.x-dev sink install
- vendor/silverstripe/cms/tests/behat/features/insert-a-link.feature:35
- vendor/silverstripe/cms/tests/behat/features/insert-a-link.feature:78
- vendor/silverstripe/cms/tests/behat/features/insert-anchor-link.feature:33
- vendor/silverstripe/elemental-bannerblock/tests/Behat/features/block-link-field.feature:18

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1787
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1474
- https://github.com/silverstripe/silverstripe-versioned/pull/454
- https://github.com/silverstripe/silverstripe-elemental/pull/1210

**Comment by maxime-rainville** [comment]
I had a look and we still have a bunch of graphQL legacy stuff in the codebase.

I don't know that we have to wait for CMS 6 to remove an of this stuff, we've already nerfed GraphQL v3 compatibility in CMS 5. If someone tried to start using "legacy" mod in CMS5 nothing would work for them.  

https://github.com/silverstripe/silverstripe-admin/blob/a3aa41cea4c4df82050eef65ad5efcfae7bfde69/client/src/boot/apollo/getGraphqlFragments.js#L24-L48

![image](https://github.com/silverstripe/silverstripe-graphql/assets/1168676/94eaef80-0500-444f-aa22-a0263a1d8d27)

**Comment by GuySartorelli** [comment]
PRs merged
