### ISSUE TITLE
Add .graphql/ to .gitignore in silverstripe/installer

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#387]
We're doing this for `public/_resources` generated through `vendor-plugin` already, so this is consistent. 
Note that we're NOT doing this for e.g. `app/_config/mysite.yml` generated through `recipe-plugin`, because those files inherently need to live in the codebase.

This "hides" the issue of a functioning Silverstripe install requiring those files from developers, but it is cleaner since it doesn't clutter version control. If you don't explicitly run `sake dev/graphql/build` *or* `sake dev/build` upon packaging a release (e.g. rsyncing to multiple servers), this can cause inconsistencies on production envs. We propose to mitigate this by adding the generation to `composer install` instead (through a composer plugin)

**Comment by unclecheese** [comment]
Just want to make a note here that this kind of locks us into the naming conventions we've chosen, which I often find a bit cumbersome in the DX:

```
_graphql/ <--- your code here
.graphql/ <--- don't touch this!
```

Might be nice to call one of them "schema" or something, so it's not so overloaded.

**Comment by chillu** [comment]
`.graphql-schema-store/`? Mentioning "store" makes it clear that this isn't a "cache".

**Comment by unclecheese** [comment]
PR here: https://github.com/silverstripe/silverstripe-graphql/pull/423

**Comment by emteknetnz** [comment]
graphql folders are gitignored - https://github.com/silverstripe/silverstripe-installer/blob/4.11/.gitignore#L7
