### ISSUE TITLE
$manager is not defined

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#4]
In the example code, you have:

``` php
        return Type::listOf($this->manager->getType('member'));        
```

But `$member` is not defined anywhere in `QueryCreator` nor its parent `FieldCreator`.

Have stolen the `getManager()` code from `Controller` and added it to `QueryCreator` as a temporary fix.

**Comment by unclecheese** [comment]
Looks like this is fixed now?

**Comment by chillu** [comment]
I've fixed this, and created an `examples/` folder to place keep those code examples runnable (eventually with some test coverage). Not very easy with the way SilverStripe manifests work though, you need to move the folder. Does that fix your issue? https://github.com/silverstripe/silverstripe-graphql/commit/db8ac2fd58f5b27ad1f3331919dabb32ad94d029
