### ISSUE TITLE
Enum fields are no longer filterable

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-graphql#405]
When updating to the latest commit on the v4 branch (aka `master`), it's no longer possible to filter by Enum fields.

I guess it is related to #398, since reverting to a previous commit solves the issue.

**Comment by emteknetnz** [comment]
@unclecheese ?

**Comment by unclecheese** [comment]
Chatted about this previously in Slack, and asked for an issue to be posted.

Minor tweak required to NestedInputBuilder, which is seeing the Enum as a complex field and skipping it, but it's actually a de factor scalar and should be treated as such.

**Comment by unclecheese** [comment]
Merged
