### ISSUE TITLE
v4 config expects ModelCreator subclass not SchemaModelCreatorInterface implementor

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-graphql#415]
The v4 documentation advises that to add a custom model creator, you need to create and then register through yaml a class implementing `SchemaModelCreatorInterface` `(https://docs.silverstripe.org/en/4/developer_guides/graphql/extending/adding_a_custom_model/).

The code falsely enforces that the class must instead subclass \SilverStripe\GraphQL\Schema\DataObject\ModelCreator.
(see: https://github.com/silverstripe/silverstripe-graphql/blob/master/src/Schema/SchemaConfig.php#L240)

**Comment by IsaacInsoll** [comment]
Thanks for doing this, can't wait for it to be fixed

**Comment by unclecheese** [comment]
Nice catch, but I have to say I'm shocked that this would ever come up. What is the use case for using a custom model creator?!

**Comment by unclecheese** [comment]
Fix is here: https://github.com/silverstripe/silverstripe-graphql/commit/b11582a84b5920887cf5d5091c00d35635701bde

**Comment by MasonD** [comment]
The architecture as-is _necessitates_ a custom model creator if you want to create a custom model. This is actually explained in the documentation quite well. https://docs.silverstripe.org/en/4/developer_guides/graphql/extending/adding_a_custom_model/#schemamodelcreatorinterface

For my specific use-case, I have a large bank of generated statistics backed by classes, and used a Model to generate types and operations for these when it would have been a lot more work to manually add types and queries solely through the yml config.

**Comment by unclecheese** [comment]
ow. That is the elusive use case we were always wondering about --  What could possibly generate types other than a dataobject? I would love to see more of that.

Makes me _really_ glad we created this layer of abstraction. It adds a bit of clutter, but I had a feeling there was a small chance non-dataobject model types could be a thing someday. Just didn't expect it so soon. 🤣
