### ISSUE TITLE
Prep GraphQL doc for go live

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#438]
The GraphQL doc needs to reflect its stable status once GraphQL v4 is stable.

# Acceptance criteria
- [x] pre-release warnings are removed.
  - [x] Because we still support v3, there should still be a link to the v3 docs (maybe in an [info] block)
- [x] The `4` branch is the default branch

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10354
- https://github.com/silverstripe/silverstripe-graphql/pull/474

**Comment by sabina-talipova** [comment]
APPROVED.
Merge after a stable release for 4.11.0

**Comment by GuySartorelli** [comment]
PRs merged.
