### ISSUE TITLE
Add a `.htaccess` file to `.graphql-generated` to dissallow any direct access to schema file

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#452]
AS a general pre-caution, it probably would be advisable to automatically create a `.htaccess` file that in the `.graphql-generated` folder that disallow any direct access to the files in there.

## ACs
- [x] If the graphql schema is inside the public directory, it cannot be accessed via a web request.

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/470

**Comment by GuySartorelli** [comment]
What should it look like?
e.g. the one in `app` is:
https://github.com/silverstripe/recipe-core/blob/4/app/.htaccess#L1-L3

Meanwhile `vendor` and `themes` don't get one at all. Is the thinking that the schema is likely to be somewhat private so should have this additional layer of protection? If so should it target `.php` specifically (as that's what the schema is saved as) or just be simple and use a blanket `Require all denied`?

**Comment by GuySartorelli** [comment]
This is necessary for the situation where the `.graphql-generated` directory is shared across servers in silverstripe cloud - declaring a shared directory in platform.yml adds it to the public folder.

**Comment by emteknetnz** [comment]
Linked PR has been merged
