### ISSUE TITLE
Prep GraphQL v4 for beta

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#455]
We're almost ready for go live.

# Acceptance criteria
- [x] All GraphQL v4 builds are green, including asset-admin, versioned-admin, elemental, versioned
- [x] A `4` branch is forked from master
- [x] All methods param and return types are updated to be strongly typed
- [x] Project using recipe-cms 4.10 are not auto upgraded to graphql v4
- [x] Composer file requires all dependencies explicitely references by codebase.

# Note 
Best way to disallow graphql 4 on recipe cms 4.10 is to require framework 4.11

# Stretch goal
- [ ] PHP 8.1 build is green (pending PHP 8.1 work being merged)

**Comment by GuySartorelli** [comment]
Probably #452 should be part of the initial stable release.

**Comment by maxime-rainville** [comment]
It's ready for beta, but the builds are grumpy. We'll fix all of that post beta
