### ISSUE TITLE
CodeGen always occurs on dev/build no matter what

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#458]
# Problem
`dev/build` will always try to recreate the `.graphql-generated` folder no matter what. This is not a problem if the process creating the folder has the appropriate permission. However, this might not always be the case: the generated code might have been created in a separate process and have different permissions.

`dev/graphql/build` has the same problem.

# Steps to reproduce
- Run a `dev/build` on a new project. The `.graphql-generated` folder gets created.
- `chmod a-w -R .graphql-generated` to remove write access.
- Run another `dev/build` on a new project.

Actual outcome: `dev/build` fails because it can't delete the existing file.
Expected outcome: Not sure ... maybe we fail gracefully. Maybe we just print a warning and declare success.

**Comment by GuySartorelli** [comment]
I'm confused as to how this is a problem... Aren't we documenting that the process that runs this needs to have write permissions to that directory?

Edit: This could be a problem for situations where developers opt to include the generated schema in their repository and for whatever reason do not want to regenerate on dev/build. It's a valid use case that our draft release documentation does mention, so we should ensure it works as expected.

**Comment by GuySartorelli** [comment]
Looks like the use case I mentioned in my previous comment is already covered.
https://github.com/silverstripe/silverstripe-graphql/blob/3a9f310b41ad29b9a23671ea172c6a17d4716513/src/Extensions/DevBuildExtension.php#L20

It would be good to mention this in the docs we produce at release-time - but we don't document all config options wherever they lie so it's not a huge deal if we don't.

So I'm back to "I don't think this is a problem - we're documenting that the process that runs this needs to have write permissions to that directory".

**Comment by GuySartorelli** [comment]
The documentation mentions how to disable this: https://docs.silverstripe.org/en/4/developer_guides/graphql/getting_started/building_the_schema/#building-on-dev-build

We've got some pretty good docs about building and deploying schema and have mentioned file permissions there as well as in the server requirements docs - I think this is okay to close now.
