### ISSUE TITLE
UpperCamelCase

### ISSUE THREAD

**Issue by Zeeshanjbd2** [silverstripe/silverstripe-graphql#469]
In old version we had **UpperCamelCase** and now we got **LowerCamelCase**, can we enable **UpperCamelCase** back using any **yml configuration** or any other way?

**Comment by lozcalver** [comment]
Can you please provide more detail or an example?

**Comment by Zeeshanjbd2** [comment]
In my old application i was using DB table i.e 
Member extends DataObject class => 
$db = [ 'Name' => 'Varchar' , 'Company' => 'Varchar' ];
now if i write read Graphql it will send response but their won't be any change in columns name according to graphql 3.8. In graphql 4 the naming convention is changed if i write Graphql it will return name, company (see how it lowers the first alphabet)

**Comment by GuySartorelli** [comment]
The formatter used for this is configurable:
https://github.com/silverstripe/silverstripe-graphql/blob/98afc6f2c6cfb64decce24ff9ff7beffbdb81f3e/src/Schema/DataObject/FieldAccessor.php#L43

You can theoretically change the callable used in that config variable to something else, and that _should_ work - though I haven't tested that.

**Comment by GuySartorelli** [comment]
I'm going to close this issue assuming that the above works - but if it doesn't, please feel free to re-open the issue and add details of exactly what doesn't work about it.
