### ISSUE TITLE
[v4] InFilter not working as expected

### ISSUE THREAD

**Issue by jordyrosenbrand** [silverstripe/silverstripe-graphql#476]
### Problem
The InFilter does not work as expected, or it is not clear how it should be used.

### Steps to reproduce
**_graphql/models.yml**
```yaml
Page:
  fields:
    id: true
    title: true
  operations:
    read: true
```
Query
```graphql
query getPages {
    readPages(filter: {
        title: {in: ["Foo", "Bar"]}
    }) {
        nodes {
            id
            title
        }
    }
}
```
As `InFilter::apply()` expects a string as value instead of an array I also tried this. But I'm not sure how this is expected to work:
```graphql
query getPages {
    readPages(filter: {
        title: {in: "Foo, Bar"}
    }) {
        nodes {
            id
            title
        }
    }
}
```
### Expected behaviour
I expect to see a result with pages that have "Foo" or "Bar" as title.
### Actual behaviour
This error is thrown:
`Argument 3 passed to SilverStripe\\GraphQL\\Schema\\DataObject\\Plugin\\QueryFilter\\Filters\\InFilter::apply() must be of the type string, array given`

**Comment by bummzack** [comment]
Yeah, the php argument type is clearly wrong. The value even gets casted back to an array: https://github.com/silverstripe/silverstripe-graphql/blob/98afc6f2c6cfb64decce24ff9ff7beffbdb81f3e/src/Schema/DataObject/Plugin/QueryFilter/Filters/InFilter.php#L19

The `string` type-hint that was added for almost all filters seems to be too restrictive. Maybe `GreaterThanOrEqualFilter` should also allow numbers? And the `NotEqualFilter` should definitely also allow `null` values.

Or is the strict typing for these params really necessary @maxime-rainville ?

**Comment by unclecheese** [comment]
It implements `ListFieldInterface` which should tell the filter plugin to put an array there, not a string. 🤔

**Comment by GuySartorelli** [comment]
PR is merged.
