### ISSUE TITLE
Schema generation error on many_many relationship

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-graphql#492]
When upgrading to Silverstripe 4.11, I get the following error on dev/build during the schema generation step. Downgrading to `silverstripe/graphql:^3` resolves the issue: `ERROR [Alert]: Uncaught SilverStripe\GraphQL\Schema\Exception\SchemaBuilderException: Config for field siteConfig.UsefulLinks must be a string representing a type, a map of config or a value of true to for type introspection from the model. in /var/www/html/vendor/silverstripe/graphql/src/Schema/Schema.php:1112`

SiteConfig.UsefulLinks is in a many_many relationship between SiteConfig and `gorriecoe/link` objects:
```
    private static $many_many = [
        'UsefulLinks' => Link::class,
        ...
    ];
```

**Comment by GuySartorelli** [comment]
What was your schema definition when you got this error? It sounds like you might have been relying on GraphQL to figure it out, and the error is saying "I can't figure it out based on what you've given me" - you might need to be more explicit in declaring the schema for this relation.

**Comment by elliot-sawyer** [comment]
I never tried to define a graphql schema, I was just relying on the $many_many and $belongs_many_many variables. I think for this issue, I ended up deleting the .graphql-generated and public/_graphql folders and it worked eventually. 

The error occasionally pops up with different many_many relationships in other projects, but I still haven't isolated a cause.

**Comment by maxime-rainville** [comment]
Is this still a problem? Did you ever managed to replicate it systematically?

**Comment by elliot-sawyer** [comment]
Haven't seen it lately in any recent versionsn of 4 or 5, probably OK to close

**Comment by elliot-sawyer** [comment]
I've run into this again on an SS4 -> SS5 upgrade. The common factor appears to be something to do with gorriecoe/silverstripe-linkfield.  Probably not worth spending much time on since there's a migration path to `silverstripe/linkfield`, so I'll focus efforts there  :+1:

**Comment by elliot-sawyer** [comment]
Sorry to beat a dead horse here, but some useful info for anyone else who stumbles across it.

I have a `many_many_extraFields` defined on this particular relation (`'Sort' => 'Int'`).  The error is caused when these are present.  If I comment them out temporarily, the site will build correctly.  When I then _uncomment_ them, the schema still builds and linkfield works normally (even the sorting, I checked).

So a bit of a non-issue with a workaround, in case anyone else stumbles across this and gets stuck

**Comment by guci0** [comment]
Set **Sort**Order, with/a "Sort" is reserved.
