### ISSUE TITLE
Split out dev/graphiql into a separate module

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#50]
It's convenient to have around, since it uses the default PHP session which means you don't need to deal with authentication (as opposed to the GraphiQL OSX app, where you need to generate your own basic auth headers).

But it's now also delivered to every SilverStripe project by default, even if only a fraction of devs will use it for development purposes. And it adds 2MB uncompressed JS.

Split this out into a separate module, and prune the commits from git to get the repo size down again (and avoid downloading this 2MB of history on every `git clone`). Yes, this will change all git SHAs, we'll survive.

**Comment by unclecheese** [comment]
Do you want the history of `dev/graphiql` commits to come over to the new repository? We could prune all of the non `graphiql` commits from the new repo, too.

**Comment by chillu** [comment]
I don't think there's too much value in retaining commit history there, depends on what's easier

**Comment by unclecheese** [comment]
Yeah, fair enough. I think it was all squashed anyway.

**Comment by chillu** [comment]
Sweet, I've ran BFG as described on https://help.github.com/articles/removing-sensitive-data-from-a-repository/, and brought down the repo size from 3.2MB to 0.2MB.
