### ISSUE TITLE
Secure endpoint by default

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#51]
At the moment, you can run introspection queries on GraphQL without any authentication. Which is fine if you've got a public API, but not necessarily a good default. While this doesn't expose any data directly, it leaks information about installed modules etc - so is a minor security issue.

Secure the endpoint by permission code instead. Permission codes should be defined on the schema configuration, since we'll eventually allow different schemas with different permissions (e.g. a stripped down "public API" with anonymous introspection capabilities)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-graphql/pull/57
