### ISSUE TITLE
Multiple schema support (SPIKE)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#52]
At the moment, `Controller` instanciates `Manager` with a hardcoded config path to the schema. Allow passing in a schema name to the controller instead, and move existing config into a `default` schema. Adjust permission code checking (https://github.com/silverstripe/silverstripe-graphql/issues/51) accordingly

## RFC
- [ ] https://github.com/silverstripe/silverstripe-graphql/issues/156

## Story
- [ ] https://github.com/silverstripe/silverstripe-graphql/issues/158

**Comment by chillu** [comment]
There's been some discussion around multiple endpoint support (which I consider the same as multiple schema support: one endpoint has one schema). The GraphQL best practices at http://graphql.org/learn/best-practices/ state:

> GraphQL is typically served over HTTP via a single endpoint which expresses the full set of capabilities of the service. This is in contrast to REST APIs which expose a suite of URLs each of which expose a single resource. While GraphQL could be used alongside a suite of resource URLs, this can make it harder to use with tools like GraphiQL.

There's discussion on the same topic for the Apollo framework as well: https://github.com/apollographql/apollo-client/issues/84. 

There's a few counter arguments to this from my perspective:

 * While you can return zero records from every auth’ed GraphQL call for anonymous users, you still run those queries and `canView()` checks.
 * You’re exposing a lot about your system internals, e.g. what modules are installed based on what queries are available. Those modules might need GraphQL for CMS operation, but that often has nothing to do with the website.
 * Generating a schema is performance intensive, and more DDoS surface for the website (although we could improve caching there).
 * Validating a schema gets [more performance intensive](http://webonyx.github.io/graphql-php/type-system/schema/) for large schemas, and that cost is paid on every call
 * But: Generating different responses for separate CMS and frontend endpoints makes caching harder if there's overlap between use cases (e.g. querying all child pages of a certain node for the CMS tree as well as a website frontend menu).

Ideally you could limit the GraphQL schema call based on authentication data passed through already. Then calls to `singleton(MyObject)->canView()` could filter out queries and types which you aren't allowed to see. But that in itself is a performance overhead - since it needs to run before every GraphQL call to keep things consistent - not only the schema metadata call. It'll also make it harder to use GraphQL tools since they typically don't allow to pass through authentication in the schema calls behind the scenes.

Overall, I still think multiple schema support is required in this module due to the relatively uncommon combination of a "wide CMS API", and a "narrower website API".

**Comment by chillu** [comment]
Bringing this forward since it'll likely impact the API surface. And we'll likely need it once we get into exposing SiteTree types, which will drastically increase the size of the GraphQL schema (and reduce it's performance, see [Cache GraphQL Schema](https://github.com/silverstripe/silverstripe-graphql/issues/130))

**Comment by unclecheese** [comment]
Story has been created based on RFC outcome https://github.com/silverstripe/silverstripe-graphql/issues/158
