### ISSUE TITLE
Support maximumLimit in pagination at a model schema level

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-graphql#543]
At the moment, you can only change the maximum limit in the overall settings. It would be nice to be able to define this at a per-model level as part of the graphql schema.

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/515
- https://github.com/silverstripe/developer-docs/pull/329

**Comment by GuySartorelli** [comment]
I've merged the code change - and I've raised a new PR which documents that change.

**Comment by emteknetnz** [comment]
Docs PR has been merged
