### ISSUE TITLE
Revert change to store GraphQL schema in cache

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#547]
The change introduced in https://github.com/silverstripe/silverstripe-graphql/pull/534 doesn't seem to be working.

With the beta release so close, it's probably best to revert this.

## Acceptance criteria
- https://github.com/silverstripe/silverstripe-graphql/pull/534 has been reverted (just revert the commits)
- Changelog reference have been removed (just revert the commits)
- Other documentation references have been removed (just revert the commits)

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/548
- https://github.com/silverstripe/developer-docs/pull/324

**Comment by GuySartorelli** [comment]
@emteknetnz Can you please link all of the PRs?

**Comment by emteknetnz** [comment]
@GuySartorelli Done

**Comment by GuySartorelli** [comment]
PRs merged. It's like we never did it in the first place
