### ISSUE TITLE
TODO: Move $authenticators to a per-schema configuration and refer to the schema from the current endpoint

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-graphql#555]
## Description
Move `$authenticators` config to a per-schema configuration and refer to the schema from the current endpoint.
See: https://github.com/silverstripe/silverstripe-graphql/blob/7684d1592f65d85816c2eb0d94f11414771b7081/src/Auth/Handler.php#L25

### Related issues:
- https://github.com/silverstripe/silverstripe-graphql/issues/58
- https://github.com/silverstripe/silverstripe-graphql/issues/52

**Comment by GuySartorelli** [comment]
Closing as a duplicate of https://github.com/silverstripe/silverstripe-graphql/issues/58
