### ISSUE TITLE
SortPlugin: Add PHP Unit tests 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-graphql#565]
## Description
It is necessary to add PHP Unit tests to check the correct operation of `SortPlugin`. It is also necessary to update the documentation and add an example of using `SortPlugin` with `has_many` fields.

## ACs
- [ ] PHPUnit tests have been added
- [ ] GraphQL section in CMS documentation has been updated with examples of using SortPlugin

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/564
- https://github.com/silverstripe/developer-docs/pull/408

**Comment by GuySartorelli** [comment]
PRs merged. This will be automatically tagged by GitHub Actions.
