### ISSUE TITLE
"Failed to remove directory - Text file busy" on any form of schema generation

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-graphql#581]
### Module version(s) affected

4.13

### Description

```
ERROR [Emergency]: Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/home/vagrant/site-name/silverstripe-cache/vagrant/.graphql-generated/._05C": rmdir(/home/vagrant/site-name/silverstripe-cache/vagrant/.graphql-generated/._05C): Text file busy
IN GET dev/graphql/build
Line 203 in /home/vagrant/site-name/vendor/symfony/filesystem/Filesystem.php
```

### How to reproduce

- dev/build in browser
- dev/build in command line
- `php vendor/silverstripe/framework/cli-script.php dev/graphql/build`

### Additional Context
I stopped php-fpm and nginx, just in case these files were in use with those, but no luck.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
I can't reproduce this - but regardless, Silverstripe CMS 4.x has entered its "security fixes only" support phase, which means it won't be getting any new bug fixes. You can find more information about this in the [major release policy](https://docs.silverstripe.org/en/5/project_governance/major_release_policy/) and the [roadmap](https://www.silverstripe.org/software/roadmap/).

If you discover this affects Silverstripe CMS 5 and can provide steps that can be reliably followed to reproduce the bug, let me know and I'll reopen this issue.
