### ISSUE TITLE
Don't encode PHP session knowledge in basic auth handler

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#60]
See https://github.com/silverstripe/silverstripe-graphql/pull/57#discussion_r96323371

 * [x] Member handler should be checked last
 * [x] BasicAuth handler should not inspect PHP session through `Member::currentUser()` in `isApplicable()`
 * ~~All handlers returning `isApplicable()` = `true` should be run, but the first one returning a valid member cuts short the loop~~
 * [ ] Handlers have a way to communicate auth failures to the client ("invalid token", "set basic auth challenge")

**Comment by robbieaverill** [comment]
@chillu - not sure I understand the request here:

>All handlers returning `isApplicable()` = `true` should be run, but the first one returning a valid member cuts short the loop

Can you clarify?

The current behaviour is to loop authenticators until one of them says that it is applicable, then stop and authenticate with it.

Are we changing this to loop all authenticators that are applicable and use the first one that successfully authenticates a request?

**Comment by chillu** [comment]
Hmmm, you're right - a basic auth handler will only say it's applicable if basic auth headers are found in the request. And in that case, it should be the *only* one handling authentication. At this point its irrelevant if the request also contains a PHP session cookie, provided you have defined basic auth with a higher priority. I've updated the ticket accordingly, so "communicate auth failures" is the only outstanding item here, right?

**Comment by robbieaverill** [comment]
Cool- yep!
