### ISSUE TITLE
Example code results in query error

### ISSUE THREAD

**Issue by ec8or** [silverstripe/silverstripe-graphql#84]
Running the example code using the following query:

`/graphql/?query={readMembers{ID+FirstName+Email}}`

results in an error:

`{"data":null,"errors":[{"message":"Cannot query field \"readMembers\" on type \"Query\".","locations":[{"line":1,"column":2}]}]}`

This is after moving the whole example directory, removing the exclude manifest file and performing a /dev/build to create the example tables.

**Comment by robbieaverill** [comment]
Hey @ec8or - could you make the change suggested in #88 and see if this fixes the examples for you? (it does for me)

**Comment by ec8or** [comment]
Yes works fine now thanks.
