### ISSUE TITLE
[Question] Silverstripe 3 support?

### ISSUE THREAD

**Issue by mooror** [silverstripe/silverstripe-graphql#92]
Note: I apologize if this is not the proper place for this question. I didn't know where else to post it. 

I was wondering if you guys are planning on making graphQL support for silverstripe 3. A colleague of mine was telling me of a silverstripe presentation he watched where the speaker had told the audience that GraphQL support was ready for 4 and there were plans to also make it available in 3. I myself have not seen or heard of this. So I wanted to ask you guys directly.

**Comment by mrgray** [comment]
This would be awesome to have!

**Comment by flamerohr** [comment]
Hi @mooror 

Although there is the idea of backporting this module to SS3, we haven't been able to prioritise it and the incentive hasn't aligned with our current plans (which has been focusing heavily on getting SS4 stable).
If someone is willing to drive and make a move for this, I'm sure someone from the team will be able to help out eventually. :)

**Comment by robbieaverill** [comment]
I'm going to close this for now since SilverStripe 3 is in limited support (security and critical bug fixes). If anyone wants to pick it up we can reopen the issue for tracking maybe, but I suspect the lack of interest in the last year indicates that it's unlikely to happen =)

**Comment by mooror** [comment]
Thank you for closing this issue @robbieaverill. The company I work for has standardized on silverstripe 4 and we therefore no longer have need of a GraphQL backport. But I thank you all for your consideration on the matter.
